# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Blackout Secure Web Application Manifest Generator
# Copyright © 2025-2026 Blackout Secure
# Licensed under Apache License 2.0
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# GitHub Marketplace Categories (selected during release UI):
# Primary: Continuous integration
# Secondary: Utilities

name: 'Blackout Secure Web Application Manifest Generator'
description: 'Generate W3C-compliant web application manifest files for Progressive Web Apps with full customization'
author: 'Blackout Secure'
branding:
  icon: 'file-text'
  color: 'blue'

runs:
  using: 'node20'
  main: 'dist/index.js'

inputs:
  # Manifest members
  name:
    description: 'Application name (displayed to users)'
    required: false
    default: ''

  short_name:
    description: 'Short application name (for limited space)'
    required: false
    default: ''

  description:
    description: 'Description of the web application'
    required: false

  # URL members
  start_url:
    description: 'URL to load when launching the app (default: /)'
    required: false
    default: '/'

  scope:
    description: 'Navigation scope of the app (default: /)'
    required: false
    default: '/'

  id:
    description: 'Unique identifier for the application'
    required: false

  # Display and orientation
  display:
    description: 'Display mode: fullscreen, standalone, minimal-ui, or browser (default: standalone)'
    required: false
    default: 'standalone'

  orientation:
    description: 'Default screen orientation: any, natural, landscape, portrait, portrait-primary, portrait-secondary, landscape-primary, landscape-secondary'
    required: false

  # Colors
  theme_color:
    description: 'Theme color for the application (hex, rgb, or named color) (default: #ffffff)'
    required: false
    default: '#ffffff'

  background_color:
    description: 'Background color while loading (hex, rgb, or named color) (default: #ffffff)'
    required: false
    default: '#ffffff'

  # Internationalization
  lang:
    description: 'Primary language tag (e.g., en-US, fr, ja)'
    required: false

  dir:
    description: 'Text direction: ltr, rtl, or auto'
    required: false

  # Icons and visual elements
  favicon:
    description: 'Enable favicon mode with default favicon settings and manifest properties (default: true). Supports any favicon format.'
    required: false
    default: 'true'

  favicon_dir:
    description: 'Directory path prefix for default favicon icons (default: /). Example: /favicons/ would generate /favicons/android-chrome-192x192.png'
    required: false
    default: '/'

  favicon_options:
    description: 'JSON object to override default favicon manifest properties (name, short_name, icons, theme_color, background_color, display, etc.). Allows customization of any manifest property.'
    required: false

  icons:
    description: 'JSON array of icon objects with src, sizes, type, and purpose properties. Not required if favicons is enabled.'
    required: false

  shortcuts:
    description: 'JSON array of shortcut objects with name, url, description, and icons properties'
    required: false

  categories:
    description: 'Comma-separated list of application categories'
    required: false

  # Asset configuration
  icons_dir:
    description: 'Default directory path for icon assets (default: /icons/). Used for convenience when building icon URLs'
    required: false
    default: '/icons/'

  # Page injection configuration
  inject_manifest_link:
    description: 'Inject manifest link into page files (default: true)'
    required: false
    default: 'true'

  crossorigin_credentials:
    description: 'Add crossorigin="use-credentials" to manifest link (default: false)'
    required: false
    default: 'false'

  inject_manifest_link_exts:
    description: 'File extensions to scan for page injection, space-separated. Recommended: html htm xhtml php phtml (default: html htm xhtml php phtml)'
    required: false
    default: 'html htm xhtml php phtml'

  favicon_validation:
    description: 'Favicon file validation mode (only in favicon mode): fail (fail action if missing), warn (warn if missing), or none (skip validation) (default: warn)'
    required: false
    default: 'warn'

  icon_validation:
    description: 'Icon file validation mode for standard icons: fail (fail action if missing), warn (warn if missing), or none (skip validation)'
    required: false
    default: 'warn'

  # Output configuration
  public_dir:
    description: 'Public directory where the manifest file will be written (e.g., dist, public, build)'
    required: true

  filename:
    description: 'Output manifest filename (default: site.webmanifest)'
    required: false
    default: 'site.webmanifest'

  # Artifact upload configuration
  upload_artifacts:
    description: 'Upload generated manifest to GitHub artifacts (default: true)'
    required: false
    default: 'true'

  artifact_name:
    description: 'Name for the uploaded artifact (default: web-manifest)'
    required: false
    default: 'web-manifest'

  artifact_retention_days:
    description: 'Number of days to retain the artifact (1-90, default: repository settings)'
    required: false

outputs:
  manifest_path:
    description: 'Path to the generated manifest file'
  manifest_json:
    description: 'Generated manifest as JSON string'
